apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground # ensures that all resources are deleted when the Application is deleted
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.5.0 # make sure to change this to the version you need
    chart: external-secrets
  destination:
    name: in-cluster
    namespace: external-secrets # you can use any namespace
  syncPolicy:
    automated:
      prune: false #  the resource is not deleted when removed from Git, to prevent accidental deletion of secrets
      selfHeal: false # manual sync is required to apply changes, giving you control over when secrets are updated
      allowEmpty: false # prevents syncing if the chart is missing or empty, avoiding unintended consequences
    syncOptions:
      - PrunePropagationPolicy=foreground # ensures that all child resources are deleted before the parent Application is deleted, preventing orphaned resources
      - Replace=false # prevents deletion and recreation of resources on updates, which is important for secrets to avoid downtime
      - PruneLast=false # ensures that resources are pruned before new ones are created, preventing conflicts during updates
      - Validate=true # ensures that resources are validated before being applied, preventing invalid configurations from being deployed
      - CreateNamespace=true # automatically creates the namespace if it doesn't exist, simplifying deployment
      - ApplyOutOfSyncOnly=false # applies all resources, not just those that are out of sync, ensuring consistency
      - ServerSideApply=true # uses server-side apply for better conflict resolution and management of resources
      - RespectIgnoreDifferences=false # ignores differences specified in the ignoreDifferences field, ensuring all changes are applied