dnsNames:
  - argocd.dev.wolffialampang.com
  - grafana.dev.wolffialampang.com
  - helloworldapp.dev.wolffialampang.com
  - userapp.dev.wolffialampang.com
  - prometheus.dev.wolffialampang.com
  - traefik.dev.wolffialampang.com