apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: pgadmin
  ports:
    - port: {{ .Values.service.port }} # port of this service
      targetPort: {{ .Values.service.port }} # port on the Pod to forward to
      protocol: TCP
  type: {{ .Values.service.type }}
