#  secretStore take responsibility to fetch the secrets from AWS Secret Manager
apiVersion: external-secrets.io/v1 #! This is use external-secrets-operator CRD, so the ESO ArgoCD app must be deployed first to register the CRD before this can be applied
kind: ClusterSecretStore # ClusterSecretStore is cluster-scoped; any namespace can reference it (e.g. traefik, monitoring)
metadata:
  name: {{ .Values.secretStore.name }} # the name you want to call the Secret Store
spec:
  provider:
    aws:
      service: SecretsManager # Means we are using AWS Secret Manager as a secret backend
      region: {{ .Values.secretStore.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }} # attach the service account to the Secret Store