apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaRoleArn }} # the IRSA role to gain access to the Secrets Manager.
  name: {{ .Values.serviceAccount.name }} # the name of the service account that will be referenced by the Secret Store