namespace: traefik

serviceAccountName: traefik-service-account

deployment:
  replicas: 2


domains:
  helloworldApp: helloworldapp.dev.wolffialampang.com
  userApp: userapp.dev.wolffialampang.com
  prometheusApp: prometheus.dev.wolffialampang.com
  argocd: argocd.dev.wolffialampang.com
  grafana: grafana.dev.wolffialampang.com
  traefik: traefik.dev.wolffialampang.com


helloworld:
  serviceName: helloworld-svc
  namespace: prod-app

argocd:
  serviceName: argocd-server   # default service name from ArgoCD install using official Helm chart
  namespace: argocd

userApp:
  serviceName: user-service
  namespace: userapp

grafana:
  serviceName: grafana-service
  namespace: monitoring

prometheus:
  serviceName: prometheus-service
  namespace: monitoring