apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app # When releaseName is not set, ArgoCD uses the Application metadata.name as the Helm release name.
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground # ensures that all resources are deleted when the Application is deleted
spec:
  project: default # mean this application belongs to the default project in ArgoCD, you can create custom projects for better organization and access control
  source:
    repoURL: https://github.com/RathomBoii/technical-refresh.git  # HTTPS — use PAT secret
    # repoURL: git@github.com:<your-user>/<your-repo>     # SSH  — use SSH key secret
    targetRevision: main
    path: eks-private-cluster/k8s/charts/app
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    name: in-cluster
    namespace: prod-app
  syncPolicy:
    automated:
      prune: true      # delete resources removed from Git
      selfHeal: true   # revert manual changes made outside Git
    syncOptions:
      - CreateNamespace=true  # auto-create prod-app namespace if not exists
