# Dev environment overrides
replicaCount: 2
image:
  repository: "687069305167.dkr.ecr.ap-southeast-7.amazonaws.com/prod-helloworld"
  tag: "v.2.10"
env: "dev"

secrets:
  enabled: true
  providerClass: "helloworld-secrets"
  mountPath: "/mnt/secrets"
  envVars:
    - name: API_KEY          # env var name the application reads
      secretName: helloworld-secrets  # K8s Secret synced by SecretProviderClass
      key: API_KEY           # key inside the K8s Secret
