# Dev environment overrides
replicaCount: 2
image:
  repository: "687069305167.dkr.ecr.ap-southeast-7.amazonaws.com/dev-helloworld"
  tag: "v.2.10"

env: "dev"
namespace: "dev-app"

secrets:
  enabled: true
  envVars:
    - name: API_KEY          # env var name the application reads
      secretName: helloworld-secrets  # K8s Secret 
      key: API_KEY           # key inside the K8s Secret
