# Prod environment overrides for secret-store chart.

secretStore:
  name: secret-store
  region: ap-southeast-7

serviceAccount:
  name: eks-secret-store-irsa
  irsaRoleArn: "arn:aws:iam::687069305167:role/prod-eks-secret-store-irsa"
  namespace: external-secrets

appExternalSecret:
  name: app-secrets      # must match secretName in app values-prod.yaml
  namespace: prod-app  
  key: "prod/app"        # AWS Secrets Manager secret name

traefikDashboardAuthExternalSecret:
  name: traefik-dashboard-auth-secret
  enabled: true
  key: "prod/traefik-dashboard-auth-secret"   # AWS SM secret name

traefikMonitoringAuthExternalSecret:
  name: traefik-monitoring-auth-secret 
  enabled: true
  key: "prod/traefik-monitoring-auth-secret"  # AWS SM secret name 

grafanaAdminExternalSecret:
  name: grafana-credentials
  enabled: true
  key: "prod/grafana/admin"   # AWS SM secret name