apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-helloworld-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-helloworld-app
  template:
    metadata:
      labels:
        app: fastapi-helloworld-app
    spec:
      serviceAccountName: helloworld-sa  # links this pod to the IAM role via IRSA
      containers:
      - name: fastapi-helloworld-app
        image: fastapi_helloworld_app:v.1.0
        imagePullPolicy: Never   # ใช้ local image
        ports:
        - containerPort: 8000