# Create the pod identity to be used by Traefik to access the Kubernetes API server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }} # <- the name of the ServiceAccount, in this case we define it as "traefik-service-account" on values.yaml
  namespace: {{ .Values.namespace }}
