# This is not Pod, it's a configuration object.
# Tell cert-manager to use Let's Encrypt to issue certificates for our Ingress resources "nginx" IngressClass.
#  it's a configuration object. It tells cert-manager: "When any Ingress in any namespace needs a cert, here's the Let's Encrypt account to use and here's the challenge method."
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuerName }}-{{ .Values.environment }} # e.g. "letsencrypt-prod"
spec:
  acme:
    # # use this while testing — unlimited requests, no rate limits
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory #  ACME server for TLS challenges
    email: {{ .Values.acmeEmail }}  # notifications for cert expiry
    privateKeySecretRef:
      name: {{ .Values.clusterIssuerName }}-{{ .Values.environment }} # e.g. "letsencrypt-prod"
    solvers:
    - http01: # Challenge solver using HTTP-01
        ingress:
          ingressClassName: {{ .Values.ingressClassName }} # Traefik handles /.well-known/acme-challenge/ on port 80
          # ingressClassName: nginx # Traefik handles /.well-known/acme-challenge/ on port 80
