apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store-aws-provider
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RathomBoii/technical-refresh.git
    targetRevision: main
    path: eks-private-cluster/k8s/charts/csi-secrets-store-aws-provider
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
